plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.fabricmc.fabric-loom-remap' version '1.17.12'
    id 'com.gradleup.shadow'
}

base {
    archivesName = "$rootProject.archives_name-$project.name"
}

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        name "IzzelAliz Maven"
        url "https://maven.izzel.io/releases/"
    }
    maven {
        name "ParchmentMC"
        url "https://maven.parchmentmc.org/"
    }
    maven {
        name "JitPack"
        url 'https://jitpack.io'
    }
    flatDir {
        dir rootProject.file('libs')
    }
    maven {
        name = 'dv8tion'
        url = 'https://m2.dv8tion.net/releases'
    }
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
}

dependencies {
    api project(':core')

    minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
    mappings loom.officialMojangMappings()

    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    implementation "net.neoforged:mergetool:2.0.0"

    compileOnly "org.projectlombok:lombok:$rootProject.lombok_version"
    compileOnly project(':processor')
    annotationProcessor "org.projectlombok:lombok:$rootProject.lombok_version"
    annotationProcessor project(':processor')
    testCompileOnly "org.projectlombok:lombok:$rootProject.lombok_version"
    testAnnotationProcessor "org.projectlombok:lombok:$rootProject.lombok_version"

    testImplementation "org.junit.jupiter:junit-jupiter:$rootProject.junit_version"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"

    api "icyllis.modernui:ModernUI-Core:$rootProject.modernui_version"
    api "icyllis.modernui:ModernUI-Markflow:$rootProject.modernui_version"
    compileOnly "maven.modrinth:modernui-mc-mvus:$rootProject.modernui_neoforge_version"

    implementation "net.jthink:jaudiotagger:3.0.1"
    implementation "dev.arbjerg:lavaplayer:$rootProject.lavaplayer_version"
    implementation "com.github.hypfvieh:dbus-java-core:$rootProject.dbus_version"
    implementation "com.github.hypfvieh:dbus-java-transport-native-unixsocket:$rootProject.dbus_version"
    implementation "com.google.zxing:core:3.5.4"
    implementation "org.apache.xmlgraphics:batik-transcoder:1.17"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += ['-Amusichud.module=' + project.name]
}

processResources {
    inputs.property("version", rootProject.version)
    filteringCharset "UTF-8"

    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    from(sourceSets.main.resources.srcDirs) {
        exclude "META-INF/mods.toml"
        exclude "fabric.mod.json"
    }
}

loom {

    runs {}
}

tasks.named('runClient') { enabled = false }
tasks.named('runServer') { enabled = false }

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
    it.options.compilerArgs += ['-Amusichud.module=' + project.name]
}

test {
    useJUnitPlatform {
        if (!project.hasProperty('integrationTests')) {
            excludeTags 'integration'
        }
    }
}

shadowJar {
    enabled = false
}
publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = base.archivesName.get()
            from components.java
        }
    }
}
