modLoader = "javafml"
loaderVersion = "[9,)"
issueTrackerURL = "https://github.com/MOPELotus/MusicHud-TuneWeave/issues"
license = "LGPL-3.0"

[[mods]]
modId = "musichud_tuneweave"
version = "${version}"
displayName = "MusicHud TuneWeave"
authors = "Etern, MOPELotus"
description = "Client music playback and synchronization powered by TuneWeave | 由 TuneWeave 驱动的客户端音乐播放与同步项目"
displayURL = "https://github.com/MOPELotus/MusicHud-TuneWeave"
logoFile = "assets/musichud_tuneweave/icon.png"

[[dependencies.musichud_tuneweave]]
modId = "neoforge"
type = "required"
versionRange = "[21.9.16-beta,21.11)"
ordering = "NONE"
side = "BOTH"

[[dependencies.musichud_tuneweave]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.9,1.21.11)"
ordering = "NONE"
side = "BOTH"

[[dependencies.musichud_tuneweave]]
modId = "modernui"
type = "required"
versionRange = "[3.12.0.5-build.4,)"
ordering = "AFTER"
side = "CLIENT"


[[mixins]]
config = "musichud_tuneweave.mixins.json"
