plugins {
    id 'java-library'
    id 'maven-publish'
    id 'com.gradleup.shadow'
    id 'xyz.jpenilla.run-paper' version '3.0.2'
}

base {
    archivesName = "$rootProject.archives_name-$project.name"
}

configurations {
    core {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom core
    runtimeClasspath.extendsFrom core
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven {
        name = 'PaperMC'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:${rootProject.minecraft_version}-R0.1-SNAPSHOT"

    core(project(path: ':core'))
    shadowBundle(project(path: ':core')) { transitive = false }

    compileOnly "io.netty:netty-buffer:4.1.118.Final"
    compileOnly "io.netty:netty-codec:4.1.118.Final"

    compileOnly "org.projectlombok:lombok:$rootProject.lombok_version"
    annotationProcessor "org.projectlombok:lombok:$rootProject.lombok_version"
    compileOnly project(':processor')
    annotationProcessor project(':processor')
    testCompileOnly "org.projectlombok:lombok:$rootProject.lombok_version"
    testAnnotationProcessor "org.projectlombok:lombok:$rootProject.lombok_version"
    testImplementation "org.junit.jupiter:junit-jupiter:$rootProject.junit_version"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-Amusichud.module=paper']
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

tasks.processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    inputs.property('version', project.version)
    inputs.property('apiVersion', rootProject.minecraft_version)
    filesMatching('paper-plugin.yml') {
        expand(
                version: project.version,
                apiVersion: rootProject.minecraft_api_version
        )
    }
    filesMatching('plugin.yml') {
        expand(
                version: project.version,
                apiVersion: rootProject.minecraft_api_version
        )
    }
}

tasks.shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = ''
}

tasks.jar { archiveClassifier = 'plain' }

tasks.assemble {
    dependsOn tasks.shadowJar
}

def paperServerJar = layout.buildDirectory.file("paper-server.jar")

tasks.register('downloadPaperServer') {
    outputs.file(paperServerJar)
    onlyIf { !paperServerJar.get().asFile.exists() }
    doLast {
        def url = 'https://fill-data.papermc.io/v1/objects/39bd8c00b9e18de91dcabd3cc3dcfa5328685a53b7187a2f63280c22e2d287b9/paper-1.21.1-133.jar'
        paperServerJar.get().asFile.parentFile.mkdirs()
        ant.get(src: url, dest: paperServerJar.get().asFile)
    }
}

tasks.runServer {
    dependsOn tasks.downloadPaperServer
    minecraftVersion("${rootProject.minecraft_version}")
    serverJar(paperServerJar)
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = base.archivesName.get()
            from components.java
        }
    }
}
